version: '3'

services:
  postgresql:
    image: postgres:latest
    container_name: lesson
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=d082x7
      - POSTGRES_DATABASE=postgres
    command: postgres
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-lesson
    ports:
      - '6379-6379'